name: .NET Build with Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    env:
      EMBEDDED_SCRIPTS_PYTHON_DLL: /usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore

    - name: Publish on version change
      id: publish_mono
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Src/EmbeddedScripts.CSharp.MonoEvaluator/EmbeddedScripts.CSharp.MonoEvaluator.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      id: publish_roslyn_scripts
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Src/EmbeddedScripts.CSharp.Roslyn.Scripting/EmbeddedScripts.CSharp.Roslyn.Scripting.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      id: publish_roslyn_compilation
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Src/EmbeddedScripts.CSharp.Roslyn.Compilation/EmbeddedScripts.CSharp.Roslyn.Compilation.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      id: publish_chakra
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Src/EmbeddedScripts.JS.ChakraCore/EmbeddedScripts.JS.ChakraCore.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      id: publish_clearscriptv8
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Src/EmbeddedScripts.JS.ClearScriptV8/EmbeddedScripts.JS.ClearScriptV8.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      id: publish_jint
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Src/EmbeddedScripts.JS.Jint/EmbeddedScripts.JS.Jint.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      id: publish_moonsharp
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Src/EmbeddedScripts.Lua.Moonsharp/EmbeddedScripts.Lua.Moonsharp.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      id: publish_pythonnet
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Src/EmbeddedScripts.Python.PythonNet/EmbeddedScripts.Python.PythonNet.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      id: publish_shared
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Src/EmbeddedScripts.Shared/EmbeddedScripts.Shared.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}